### ISSUE TITLE
TypeError: Cannot convert undefined or null to object opentok.js:23

### ISSUE THREAD

**Issue by lulersoft** [opentok/cordova-plugin-opentok#83]
TypeError: Cannot convert undefined or null to object
opentok.js:23
    at slice (<anonymous>)
    at a (http://localhost:8000/opentok.js:23:114633)
    at c (http://localhost:8000/opentok.js:23:115132)
    at new u (http://localhost:8000/opentok.js:23:115169)
    at e.exports (http://localhost:8000/opentok.js:23:114416)
    at Object.Node.o.name.c.request (http://localhost:8000/opentok.js:23:121100)
    at Object.Node.o.name.c.post (http://localhost:8000/opentok.js:23:121521)
    at u (http://localhost:8000/opentok.js:23:317041)
    at e (http://localhost:8000/opentok.js:23:317245)
    at l (http://localhost:8000/opentok.js:23:317486)

**Comment by msach22** [comment]
@lulersoft Could you please provide more details as to when this happens? Could you also share your implementation?

**Comment by msach22** [comment]
@lulersoft I'm closing this issue due to the inactivity. Please re-open with more details if the issue still persists.
